### ISSUE TITLE
inconsistency between meta data and data products in jemx products

### ISSUE THREAD

**Issue by ferrigno** [andreatramacere/oda_api#2]
meta data indicates isgri_spectrum, but it is jemx, see below

data=disp.get_product( sw_list='010200160010.001,010200170010.001,010200200010.001',
                             instrument="jemx",
                             jemx_num='1',
                             product="jemx_spectrum", 
                             product_type="Real", 
                             osa_version='OSA10.2',
                             E1_keV=3.0,
                             E2_keV=20.0)

for dd in data._p_list:
    dd.show_meta()
    dd.show()

------------------------------
src_name : Crab
product : isgri_spectrum
------------------------------
------------------------------
name: 
meta_data dict_keys(['src_name', 'product'])
number of data units 2
------------------------------
data uniti 0 ,name: PRIMARY
data uniti 1 ,name: JMX1-PHA1-SPE
------------------------------
src_name : Crab
product : jemx_arf
------------------------------
------------------------------
name: 
meta_data dict_keys(['src_name', 'product'])
number of data units 2
------------------------------
data uniti 0 ,name: PRIMARY
data uniti 1 ,name: SPECRESP
------------------------------
src_name : Crab
product : jemx_rmf
------------------------------
------------------------------
name: 
meta_data dict_keys(['src_name', 'product'])
number of data units 6
------------------------------
data uniti 0 ,name: PRIMARY
data uniti 1 ,name: GROUPING
data uniti 2 ,name: SPECRESP MATRIX
data uniti 3 ,name: EBOUNDS
data uniti 4 ,name: JMX1-AXIS-ARF
data uniti 5 ,name: JMX1-IMAG-ARF

**Comment by andreatramacere** [comment]
Hi Carlo,
thanks for pointing out this,  anyhow this has to be fixed in cdci osa plugin for Jemx, so I am closing this because it is not an issue with the oda api. I have changed in:

https://gitlab.astro.unige.ch/cdci/cdci_osa_plugin/blob/api_multiprod/cdci_osa_plugin/osa_spectrum_query.py
at line 150:
```
FROM-> meta_data['product'] = 'isgri_spectrum'
TO->  meta_data['product'] = 'jemx_spectrum'
```

I have done the change and merged the development brach (api_multiprod) to staging1.2 and production 1.2. Now Volodymyr should integrate this on the open stack. Should we open a ticket on the redmine or just ask to Volodymyr to do the integration?
Cheers
   Andrea
