### ISSUE TITLE
plot image in sky coordinates ?

### ISSUE THREAD

**Issue by ferrigno** [andreatramacere/oda_api#3]
I have reused a function implemented by Volodymyr in the QLA to plot the image in celestial coordinaets.

https://gitlab.astro.unige.ch/cdci/oda_api_wrapper/commit/ff1badd0cc3262c68ea7891b656318704b1f3843

The current method from oda_api plots the image in image coordinates.
from oda_api.plot_tools import OdaImage
im=OdaImage(data.mosaic_image_0)
im.show(unit_ID=1)

Maybe, you could implement the plotting in mage coordinates

**Comment by andreatramacere** [comment]
Hi Carlo,
the API helper functions, are meant to give a quick look view of products. Adding sky coordinate is very easy, at the same time I don't want overload these functionalities because they might become more difficult to be generalised for several instruments. We need to find a trade-off that
is safe enough in order to allow that a single person can mantain more than 10 repositories.
In this case I think that the functionality can still fit, but in general we should not re-implement things that are already available. 
https://docs.astropy.org/en/stable/visualization/wcsaxes/
```python
from astropy.wcs import WCS
from astropy.io import fits`
from astropy.utils.data import get_pkg_data_filename

filename = get_pkg_data_filename('galactic_center/gc_msx_e.fits')

hdu = fits.open(filename)[0]
wcs = WCS(hdu.header)

plt.subplot(projection=wcs)
plt.imshow(hdu.data, vmin=-2.e-5, vmax=2.e-4, origin='lower')
plt.grid(color='white', ls='solid')
plt.xlabel('Galactic Longitude')
plt.ylabel('Galactic Latitude')
```
